// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErj61tOLWLIV0nZP3aYBPdG8ynhEkfQs',
    appId: '1:691328470279:web:291d9982a02d8480e009a2',
    messagingSenderId: '691328470279',
    projectId: 'mycloset-3e508',
    authDomain: 'mycloset-3e508.firebaseapp.com',
    storageBucket: 'mycloset-3e508.firebasestorage.app',
    measurementId: 'G-M53PM14YDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABBobf9rYvewS-QhctsVObQzsacXhNIQs',
    appId: '1:691328470279:android:58a3b7c39765d60be009a2',
    messagingSenderId: '691328470279',
    projectId: 'mycloset-3e508',
    storageBucket: 'mycloset-3e508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxm50Qd4qQ_YEM_VukMibgt75yfC9EDtA',
    appId: '1:691328470279:ios:81516a80fe41abe0e009a2',
    messagingSenderId: '691328470279',
    projectId: 'mycloset-3e508',
    storageBucket: 'mycloset-3e508.firebasestorage.app',
    iosBundleId: 'com.example.closely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxm50Qd4qQ_YEM_VukMibgt75yfC9EDtA',
    appId: '1:691328470279:ios:81516a80fe41abe0e009a2',
    messagingSenderId: '691328470279',
    projectId: 'mycloset-3e508',
    storageBucket: 'mycloset-3e508.firebasestorage.app',
    iosBundleId: 'com.example.closely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAErj61tOLWLIV0nZP3aYBPdG8ynhEkfQs',
    appId: '1:691328470279:web:4aed6530e2bb4792e009a2',
    messagingSenderId: '691328470279',
    projectId: 'mycloset-3e508',
    authDomain: 'mycloset-3e508.firebaseapp.com',
    storageBucket: 'mycloset-3e508.firebasestorage.app',
    measurementId: 'G-R7FWGDM5F6',
  );
}
